name: TelegramBots CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: write-all

jobs:
  build_application:
    name: Compile with JDK 17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 17
          maven-version: 3.9.6

      - name: Build Maven Application
        shell: bash
        run: mvn clean install

      - name: Create SBOM For hutool-all
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./telegrambots-test-reports/target/
          artifact-name: telegrambots.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Tar Maven Build Repository
        shell: bash
        run: tar -czf maven-build.tgz -C ~ .m2/repository

      - name: Upload Maven Build Repository
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: maven-build.tgz

      - name: Generate Maven Dependency Tree
        shell: bash
        run: mvn dependency:tree -DoutputFile=maven_dep_tree.txt

      - name: Create Maven Dependency Tree Zip File
        shell: bash
        run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r mvn-dependency-tree.zip {} +

      - name: Upload Maven Dependency Tree Zip
        uses: actions/upload-artifact@v4
        with:
          name: maven-dependency-tree
          path: mvn-dependency-tree.zip

  run_sca_scanning:
    needs: [ build_application ]
    name: Run SCA Scanning Workflow
    uses: seansmith39/H6060-Experiment-1-SCA-Scans/.github/workflows/sca_scan_mvn.yml@v1.0.4
    secrets: inherit
    with:
      project-name: telegrambots
      java-version: 17
      java-distribution: zulu
      mvn-build-artifact: maven-build
      maven-setup-required: true

  run_sast_scanning:
    needs: [ build_application ]
    name: Run SAST Scanning Workflow
    uses: seansmith39/H6060-Experiment-1-SAST-Scans/.github/workflows/sast_scan_mvn.yml@v1.0.3
    secrets: inherit
    with:
      sonarqube-project-name: H6060-TelegramBots
      mvn-build-command: mvn clean install
      jacoco-scan-enabled: false
      jacoco-coverage-file: 'telegrambots-test-reports/target/site/jacoco-aggregate/jacoco.xml'
      java-version: 17
      java-distribution: zulu
      maven-setup-required: true
